font_family Maple Mono SemiBold

shell_integration no_cursor
cursor_shape beam

window_padding_width 7
window_padding_height 10

scrollback_lines 3000

font_size 11

map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

background_opacity 0.9

background           #141414
foreground           #e8e6e3

selection_background #f96900
selection_foreground #141414

color1   #ff4422   #errors 
color2   #b8c46e   #success/git add
color3   #f96900   #Warnings/modified
color4   #4f7aa9   #directories
color6   #a08878   #special files
color8   #555555   #comments/dim text